export const ADD_CHANNEL_REQUEST = "ADD_CHANNEL_REQUEST";
export const ADD_CHANNEL_SUCCESS = "ADD_CHANNEL_SUCCESS";
export const ADD_CHANNEL_FAILURE = "ADD_CHANNEL_FAILURE";

export const FETCH_CHANNELS_REQUEST = "FETCH_CHANNELS_REQUEST";
export const FETCH_CHANNELS_SUCCESS = "FETCH_CHANNELS_SUCCESS";
export const FETCH_CHANNELS_FAILURE = "FETCH_CHANNELS_FAILURE";

export const JOIN_CHANNEL_REQUEST = "JOIN_CHANNEL_REQUEST";
export const JOIN_CHANNEL_SUCCESS = "JOIN_CHANNEL_SUCCESS";
export const JOIN_CHANNEL_FAILURE = "JOIN_CHANNEL_FAILURE";

export const GET_CHANNEL_BY_ID_REQUEST = "GET_CHANNEL_BY_ID_REQUEST";
export const GET_CHANNEL_BY_ID_SUCCESS = "GET_CHANNEL_BY_ID_SUCCESS";
export const GET_CHANNEL_BY_ID_FAILURE = "GET_CHANNEL_BY_ID_FAILURE";