export const CHECK_USER_JOINED_CHANNEL_REQUEST = "CHECK_USER_JOINED_CHANNEL_REQUEST";
export const CHECK_USER_JOINED_CHANNEL_SUCCESS = "CHECK_USER_JOINED_CHANNEL_SUCCESS";
export const CHECK_USER_JOINED_CHANNEL_FAILURE = "CHECK_USER_JOINED_CHANNEL_FAILURE";